### ISSUE TITLE
Zone support

### ISSUE THREAD

**Issue by nathanvdh** [nathanvdh/homeassistant-airtouch2plus#2]

**Comment by nathanvdh** [comment]
@Chris112 @Selmaks @bigjezza @phardy @ozhound @ctrl-freak @mcoops

Ping :)

Can somebody see if the latest beta release works at all. If so: 
Do you get fan entities for the zones
Does on/off show correctly
Does damper% show correctly

**Comment by ctrl-freak** [comment]
I'm getting an error importing At2PlusClient, but I'll remove it entirely and try again.

```
This error originated from a custom integration.

Logger: homeassistant.setup
Source: custom_components/airtouch2plus/__init__.py:4
Integration: airtouch2plus
First occurred: 6:56:29 PM (1 occurrences)
Last logged: 6:56:29 PM

Setup failed for custom integration airtouch2plus: Unable to import component: cannot import name 'At2PlusClient' from partially initialized module 'airtouch2.at2plus.At2PlusClient' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/airtouch2plus/__init__.py", line 4, in <module>
    from airtouch2.at2plus import At2PlusClient
  File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/__init__.py", line 1, in <module>
    from airtouch2.at2plus.At2PlusClient import At2PlusClient
  File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py", line 6, in <module>
    from airtouch2.at2plus.At2PlusGroup import At2PlusGroup
  File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusGroup.py", line 3, in <module>
    from airtouch2.at2plus.At2PlusClient import At2PlusClient
ImportError: cannot import name 'At2PlusClient' from partially initialized module 'airtouch2.at2plus.At2PlusClient' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py)
```

**Comment by Chris112** [comment]
Hey, i'm excited for this one. I did the update via HACS but didn't check the sha. Got the same error as @ctrl-freak 

```
Logger: homeassistant.setup
Source: setup.py:215
First occurred: 6:55:42 PM (1 occurrences)
Last logged: 6:55:42 PM

Setup failed for custom integration airtouch2plus: Unable to import component: cannot import name 'At2PlusClient' from partially initialized module 'airtouch2.at2plus.At2PlusClient' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
    component = integration.get_component()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
    ComponentProtocol, importlib.import_module(self.pkg_path)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/config/custom_components/airtouch2plus/__init__.py", line 4, in <module>
    from airtouch2.at2plus import At2PlusClient
  File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/__init__.py", line 1, in <module>
    from airtouch2.at2plus.At2PlusClient import At2PlusClient
  File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py", line 6, in <module>
    from airtouch2.at2plus.At2PlusGroup import At2PlusGroup
  File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusGroup.py", line 3, in <module>
    from airtouch2.at2plus.At2PlusClient import At2PlusClient
ImportError: cannot import name 'At2PlusClient' from partially initialized module 'airtouch2.at2plus.At2PlusClient' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py)
```

**Comment by randellmatt** [comment]
Same for me unfortunately. Looking forward to steps toward zone control - that would be amazing.

2023-11-01 21:29:59.133 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration airtouch2plus: Unable to import component: cannot import name 'At2PlusClient' from partially initialized module 'airtouch2.at2plus.At2PlusClient' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py)
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 215, in _async_setup_component
component = integration.get_component()
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/loader.py", line 818, in get_component
ComponentProtocol, importlib.import_module(self.pkg_path)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
return _bootstrap._gcd_import(name[level:], package, level)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
File "<frozen importlib._bootstrap_external>", line 940, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "/config/custom_components/airtouch2plus/__init__.py", line 4, in <module>
from airtouch2.at2plus import At2PlusClient
File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/__init__.py", line 1, in <module>
from airtouch2.at2plus.At2PlusClient import At2PlusClient
File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py", line 6, in <module>
from airtouch2.at2plus.At2PlusGroup import At2PlusGroup
File "/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusGroup.py", line 3, in <module>
from airtouch2.at2plus.At2PlusClient import At2PlusClient
ImportError: cannot import name 'At2PlusClient' from partially initialized module 'airtouch2.at2plus.At2PlusClient' (most likely due to a circular import) (/usr/local/lib/python3.11/site-packages/airtouch2/at2plus/At2PlusClient.py)

**Comment by nathanvdh** [comment]
This is what I get for not writing an emulator to test against myself...

Ok fixed this recursive import problem. Try again :)

**Comment by randellmatt** [comment]
Reloaded. Cannot see any new entities.

**Comment by nathanvdh** [comment]
I think I know what's going on. I'll try to sort it out tomorrow. In the meantime can you try the `test_programs/at2plus_test.py` script from the library repo. Let me know if it prints the zone statuses correctly.

**Comment by nathanvdh** [comment]
Ok pushed another release that actually requests the zone info xD.

**Comment by randellmatt** [comment]
Still no new entities or zone details unfortunately.

**Comment by nathanvdh** [comment]
Final dumb mistake fixed for tonight - try 0.2.3. Will pick this up again tomorrow night.

**Comment by randellmatt** [comment]
I can now see 8 fan group entities corresponding to the 8 zones of my house. They update correctly if I turn a zone on and off. No dampler settings or anything else. It's a pretty good start though!

**Comment by ctrl-freak** [comment]
Confirming the later update is good.

All zones accounted for, no dampening, but that's still awesome!

**Comment by mcoops** [comment]
Agreed!

Works, fans are correct (on/off) but no dampening %. Very exciting!

**Comment by Selmaks** [comment]
Just confirming what everyone else is seeing. Very exciting indeed!.

**Comment by nathanvdh** [comment]
Have a go with the latest release :)

**Comment by randellmatt** [comment]
So far it looks to be operating correctly. I can control each individual zone damper %; and turn zones off and on. 

This will be very helpful to control the zones for the kids overnight when asleep and cold or the opposite during the day when warm. Awesome.

**Comment by randellmatt** [comment]
100% setting works now with the newest version. Sometimes the updated values are not reflected immediately on the air touch app, but that may be more to do with the app itself.

**Comment by nathanvdh** [comment]
Sorry I'm not sure about that. Group names should be working in new version now.

**Comment by ctrl-freak** [comment]
Group names there, percent control accurate and changing it reflects in the app.

Fantastic work 👌👌
