### ISSUE TITLE
Unknown message types 0x45/0x2b

### ISSUE THREAD

**Issue by aplund** [nathanvdh/homeassistant-airtouch2plus#3]
I get these known message type errors, but the integration generally seems to work.  They tend to repeat periodically.  I'm using the version tagged v0.2.6

```2024-01-02 15:45:49.864 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x45)
Traceback (most recent call last):
  File "/var/lib/hass/.venv/lib/python3.11/site-packages/airtouch2/protocol/at2plus/control_status_common.py", line 74, in from_bytes
    subtype = ControlStatusSubType(subheader_bytes[0])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 69 is not a valid ControlStatusSubType
2024-01-02 15:45:49.876 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=45:00:00:34:00:00:00:00:41:43:34:38:00:00:00:00:00:00:00:00:00:00:00:00:18:00:00:00:23:0c:00:00:00:00:00:00:00:00:00:00:41:74:63:68:32:50:4d:00:36:17:22:48:22:00:22:02:00:00:00:00
2024-01-02 15:45:51.700 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x2b)
Traceback (most recent call last):
  File "/var/lib/hass/.venv/lib/python3.11/site-packages/airtouch2/protocol/at2plus/control_status_common.py", line 74, in from_bytes
    subtype = ControlStatusSubType(subheader_bytes[0])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 712, in __call__
    return cls.__new__(cls, value)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/enum.py", line 1135, in __new__
    raise ve_exc
ValueError: 43 is not a valid ControlStatusSubType
2024-01-02 15:45:51.708 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=2b:00:00:00:00:04:00:06:80:80:07:ff:81:81:07:ff:82:82:07:ff:83:83:07:ff:90:ff:02:f1:91:ff:07:ff```

**Comment by nathanvdh** [comment]
Yeah it's expected, you have some newer version of the protocol with messages that I don't have documentation for. I didn't want to silently ignore them. I'm not going to reverse engineer the airtouch2+ protocol / work out what they are, as I don't have a 2+ system and have no motivation. I will leave this issue open in case someone else ever wants to try and work stuff like this out.

If anyone is missing a feature they would like then I am happy to help get it working.

**Comment by nathanvdh** [comment]
@aramshaw you need to find out what causes the message to be sent (is it periodic, does it happen when something changes, what change triggers the message to be sent), that will give you the first clue about what the message is. Then you need to work out what the contents of the message are, you basically want to dump the contents every time you receive it (you can see the contents printed as hex in the log message above) and see what has changed between each message, and whether you did something to cause that change. `vbindiff` is a good simple TUI interface for doing diffs on binary files, [ImHex](https://github.com/WerWolv/ImHex) is a more powerful GUI tool.

E.g. if you were reverse engineering a message that contained the aircon's set temperature, it would probably be sent every time you change the set temperature, and if you increased the temperature by 1 degree you would probably see a value in the messsage contents go up by 1.

**Comment by aramshaw** [comment]
@nathanvdh - this is a bit more than I was expecting - hex decoding!

Let me have a look and see what I can do but no promises it's a bit above my pay grade.

**Comment by nathanvdh** [comment]
Yeah reverse engineering is a pretty difficult task. There was a specification document that I was working from (posted in this thread https://community.home-assistant.io/t/airtouch-2-plus/263744)  for airtouch2+ but this message wasn't in it... Hence why it's not implemented. I don't even have an airtouch2+ system so I couldn't even reverse engineer it myself if I wanted to.

Maybe the fact that it's something that's NOT in that documentation will be a hint to what it is? But who knows... maybe there's similar state in a different message.

**Comment by gavintweedie** [comment]
Version 0.2.10
I've found a bit of a pattern with this error. I've noticed my aircon seemingly not cooling as well, but everything looks fine.

Then I notice on the temp graph for the airtouch that it hasn't changed for hours, too level... and it corresponds with a change in the 0x2b errors. The 0x2b errors are periodic, normally every 30seconds but occasionally a minute apart. Some form of keepalive perhaps?

Happy to grab more captures or try and provide information that might help identify what it is.

For example,
<img width="1191" alt="Image" src="https://github.com/user-attachments/assets/6cbace41-78eb-456f-afd6-a397999ec708" />

2025-03-25 16:21:19.130 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x2b)
2025-03-25 16:21:19.131 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=2b:00:00:00:00:04:00:06:80:80:07:ff:81:81:07:ff:82:82:07:ff:83:83:07:ff:90:ff:02:dc:91:ff:07:ff
2025-03-25 16:21:49.276 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x2b)
2025-03-25 16:21:49.277 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=2b:00:00:00:00:04:00:06:80:80:07:ff:81:81:07:ff:82:82:07:ff:83:83:07:ff:90:ff:02:dd:91:ff:07:ff
2025-03-25 16:23:49.614 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x2b)
2025-03-25 16:23:49.615 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=2b:00:00:00:00:04:00:06:80:80:07:ff:81:81:07:ff:82:82:07:ff:83:83:07:ff:90:ff:02:dc:91:ff:07:ff
<... no errors ..>
**2025-03-25 17:44:28.753 WARNING (MainThread) [airtouch2.common.NetClient] Connection lost, reconnecting**
2025-03-25 17:45:34.223 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x2b)
2025-03-25 17:45:34.223 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=2b:00:00:00:00:04:00:06:80:80:07:ff:81:81:07:ff:82:82:07:ff:83:83:07:ff:90:ff:02:db:91:ff:07:ff
2025-03-25 17:46:04.232 WARNING (MainThread) [airtouch2.protocol.at2plus.control_status_common] Unknown message type in header (0x2b)
2025-03-25 17:46:04.232 WARNING (MainThread) [airtouch2.at2plus.At2PlusClient] Unknown status message type: subtype=0, data=2b:00:00:00:00:04:00:06:80:80:07:ff:81:81:07:ff:82:82:07:ff:83:83:07:ff:90:ff:02:da:91:ff:07:ff

**Comment by aramshaw** [comment]
@nathanvdh - FYI - am working on this. There are a few new message types I working on de-coding. I also uncovered that when the messages are not handled it can interfere with getting the A/C active.

Unknown message type in header (0x2b) - seems to be the availability of the Favourites - which are basically shortcuts for fan settings across the zones, e.g. night time, day time. 

Another new message type is # 0x31 -this is a status for the Favourites - what is active now

**Comment by gavintweedie** [comment]
@aramshaw how are you progressing with this? I have no favourites setup but still get the 0x2b. Do you have them setup?

**Comment by aramshaw** [comment]
@gavintweedie - Honestly I did okay but got a bit stuck and haven't closed it out. I was able to get to the 0x2b message structure but I made so many changes to the code to generate de-bug messaging that backing it out to make a clean pull request became too big a task. I'll have another go over the next couple of weeks.

**Comment by aramshaw** [comment]
@nathanvdh @gavintweedie  - I did some more work on this (with substantial assistance from Claude) and seem to have fixed the issue.

(I also just saw this thread: https://github.com/nathanvdh/homeassistant-airtouch2plus/issues/5 and the spec there. More notes below)

## What I Found
- **5 unknown message types** (0x2B, 0x31, 0x10, 0x40, 0x27) that seem to require proper acknowledgments
- These messages are not in the spec referenced above.
- Without these ACKs, the controller refuses new connections from both HA and mobile apps
- Complete protocol documentation with working implementation

## What I did
I'm a 100% newbie to contributing to public git projects so I forked the original code to a repo on my git account and made the changes to a branch there: https://github.com/aramshaw/airtouch2-python/tree/fix-undocumented-airtouch2%2Bcommands

It includes 
- docs on the protocol 
- a fix for the unknown message types that I have been running for 48hrs with no new errors.

BTW I tweaked homeassistant-airtouch2plus that I used to be able to edit and update the airtouch2 package locally. Basically I copy the airtouch2 SRC files into a sub-directory of the airtouch2plus custom_compontent so the integration references those instead of the installed. 

@nathanvdh - let me know if you want to use this as I just saw the updates on the other thread and I'm not sure how you want it included.

**Comment by gavintweedie** [comment]
@aramshaw seems you've made some good progress. I'm seeing much less disconnections/unavailabilities with my TCP keepalive changes too, however I did have one today and it lined up with a 0x2b error which I think your changes will solve by acking as required.

I wonder if your changes will negate the need for the keepalives completely. I'm going to run another couple of days with my changes, then I might revert to the your version without keepalives and I'll give you some feedback. I'm running airtouch2+ FYI. Which unit do you have to rest against?

**Comment by aramshaw** [comment]
@gavintweedie - I think the root cause of unavailability is not ack'ing some message types, especially on first connection. I found in testing that doing the wrong thing would basically stop the Airtouch2+ from communicating at all to either HA or mobile app. In one case I needed to power cycle the controller to get the mobile app working again.  My HA-Airtouch2+ connection seems stable now.

Not sure of the question you're asking but this is my Airtouch2+ system details.
<img width="305" height="157" alt="Image" src="https://github.com/user-attachments/assets/76656d7c-9de7-47ae-b6d3-21b7cf38195c" />
 
Happy to help.

**Comment by gavintweedie** [comment]
@aramshaw I think you are right. The last ~40hrs I've had no periods of graphs not updating but I do have this logged 4 times recently that wasn't logging before implementing keepalives:
```
Logger: airtouch2.common.NetClient
Source: runner.py:154
First occurred: July 25, 2025 at 6:58:07 PM (4 occurrences)
Last logged: 1:44:53 AM

Connection lost, reconnecting
```

I think what's happening is:
1. Failure to Ack by client is causing device to silently lock/drop/ignore **all** messages on existing TCP sessions.
2. Because the TCP session isn't actually closed in any way, the NetClient side thinks it's still available and keeps sending commands there which get ignored by the device.
3. Keepalives aren't stopping the sessions dropping they are actually discovering that the far end is not replying and dropping the TCP session on the client, causing the client to establish a new TCP session which isn't "locked" from step 1. This also makes sense as I found I could always recover the addon by "reloading" the plugin, which created a new TCP session.

I think 3 is allowing detection of the issue and repair of bad TCP session through reconnect, while 1 is fixing root cause.

I think we should consider both to catch other reasons for TCP sessions breaking (NAT timeouts etc) which should be much more rare than what your fix for this root cause will be.  I think I'll submit the keepalive stuff under a different PR not the unknown message ones because the keepalive fix is in NetClient which lives in https://github.com/nathanvdh/airtouch2-python not here

My version is the same as yours, however MHI AC being controlled:

<img width="732" height="448" alt="Image" src="https://github.com/user-attachments/assets/4bcc0dfe-8632-40f7-92bd-093bc9046b64" />

Will fire up your code (without my keepalive addon) today and run it for a few days and let you know how I go.

**Comment by aramshaw** [comment]
@gavintweedie - I think you're far more experienced at this than I so I'll take your advice.

Note that the branch with my changes is here: https://github.com/aramshaw/airtouch2-python/tree/fix-undocumented-airtouch2%2Bcommands

Not sure how you're handling using the local airtouch2 library instead of pip version but I put it in a sub-directory and use it when the directory exists. See this branch: https://github.com/aramshaw/homeassistant-airtouch2plus/tree/fix-undocumented-commands

Let me know if there is a better way. 

I hope I'm doing this correctly.

**Comment by aramshaw** [comment]
@gavintweedie - new commit today to support unknown message type (0x45) with some debugging data dump to try to work out what it is.

**Comment by gavintweedie** [comment]
I've manually replaced the pip distributed files in the docker container with your modifications, couldn't find a simple way to do it and as its only a couple of files easy enough to copy over. I've grabbed your changes from today and now running your modified code. WIll report back over the next few days if I see any errors logged or other issues.

And no, I'm quite the python beginner too. Blind leading the blind here @aramshaw  :)

**Comment by gavintweedie** [comment]
Edit: a couple more days data

@aramshaw been running your code changes a few days, and also included keepalives into your code on my home setup.

This is how my logs look for disconnects the past few days:
```
# journalctl  | grep air | grep reconn | cut -c 1-6 |uniq -c
      2 Jul 22
      2 Jul 23
      2 Jul 24
      5 Jul 25
      3 Jul 26
      1 Jul 27 (this one was a reload by me - self inflicted)
     (0 for Jul 29)
      1 Jul 29 (this one was a reload by me - self inflicted)
      7 Jul 30
      3 Jul 31
      4 Aug 01
      3 Aug 02
      3 Aug 03 (two caused by reloads by me - self inflicted)


```
And Unknown mesages:
```
# journalctl  | grep air | grep Unknown | cut -c 1-6 | uniq -c
    840 Jul 22
   1016 Jul 23
    940 Jul 24
    870 Jul 25
   1066 Jul 26
    692 Jul 27
      8 Jul 28
(0 for Jul 29)
(0 for Jul 30)
(0 for Jul 31)
(0 for Aug 01)
(0 for Aug 02)
(0 for Aug 03)

```

Functionality wise everything seems fine, it's winter here so haven't tested cooling just heating. On/Off/Zone control etc all fine. Will run for a few more days. Keen to hear how its going for you.

**Comment by gavintweedie** [comment]
@aramshaw this is looking pretty good. I've edited my past post with how the errors are looking and its a vast improvement.

I assume its working equally well for you?

Would you consider pushing a patch upstream with your changes?

**Comment by aramshaw** [comment]
@gavintweedie - sadly I'm still having problems. I think my phone app and HA are interacting where the phone app is ack'ing some messages so it works intermittently but not reliably. I'm just about to fire up Wireshark. Wish me luck as I've never used it before. #steeplearningcurve.

**Comment by gavintweedie** [comment]
@aramshaw FYI I do not use the airtouch phone app at all. I use home assistant app to control it, or the panel on the wall.

I assumed that using the app + another device at the same time might cause issues. I don't have an easy way to see if multiple phones would also cause issues with each other. I do have the app installed, so can capture something if you'd like me to simulate something you are experiencing if you tell me the steps to reproduce.

**Comment by aramshaw** [comment]
@gavintweedie - I use the phone app to make changes and see if HA syncs to it. I'm getting into the weeds of Wireshark and got some interesting stuff yesterday. No need for you to capture anything at the moment. I'm way out of my comfort zone with ARP Spoofing and such but I'm putting it down to a "good learning experience". I'll keep going and keep you updated.

**Comment by gavintweedie** [comment]
I did a home assistant upgrade a few days ago and forgot about the manual changes I made with keepalives and your patches @aramshaw and the issues all came immediately back.

- Disconnects (and thus no temp updates)
- Various unknown message types

Yesterday I applied your patches back, but forgot my keepalive fixes, and the unknown message types went away but I did get 1 phantom disconnect while the aircon was off this morning. I've put the keepalive fixes in now.

Certainly confirmed for me how much of an improvement your patches make.

**Comment by aramshaw** [comment]
@gavintweedie - honestly I'm not confident in my code additions for a broader audience yet. I need to do some more work on them. I've made a couple more minor changes and functionality has gone backwards. I see you pushed a PR - I'll keep working to improve my stuff. Don't want to risk pushing something the takes people backwards.

**Comment by aramshaw** [comment]
@gavintweedie and @nathanvdh - I've just added a PULL request to the the https://github.com/nathanvdh/airtouch2-python repo that fixes, I believe, the 0x45 and 0x2b message issues. It's been running for a few days for me and has had no issues. It's happy running along side the mobile app and local control.

This is my *first ever* public contribution so please review carefully. Hopefully the code and comments are not too terrible.

Also included is a document with the findings.

FYI - turns out Wireshark was a complete red herring. It was never needed.

**Comment by gavintweedie** [comment]
It's @nathanvdh 's repo so acceptance is entirely up to him but I've been super impressed with the improvements you've made @aramshaw .

I assume Nathan will need to accept and bump the version, then bump the required version in the HA packages so they pull the updated airtouch2-python code.

**Comment by aramshaw** [comment]
Thanks @gavintweedie - I'm reasonably confident in this code. It's much better (it actually works properly) than what I shared on my repo with you.
