### ISSUE TITLE
2025.1 broke the fan entities

### ISSUE THREAD

**Issue by rgogada** [nathanvdh/homeassistant-airtouch2plus#8]
Fans won't turn on/off. here is the log message.

Logger: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:287
integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 6:01:01 PM (1 occurrences)
Last logged: 6:01:01 PM

[140707797808992] Entity fan.rishiroom does not support action fan.turn_on

Pls let me know if you need any further info. Cheers.

**Comment by rgogada** [comment]
enabled debug and I could see below message at the end.

2025-01-04 19:53:42.390 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_protocol.py", line 480, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_app.py", line 569, in _handle
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.13/site-packages/aiohttp/web_middlewares.py", line 117, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 210, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 86, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 222, in post
    return await super().post(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 74, in wrapper
    return await method(view, request, data, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 122, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 341, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 388, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        flow, cur_step["step_id"], user_input
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 491, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/airtouch4/config_flow.py", line 34, in async_step_user
    await airtouch.UpdateInfo()
  File "/usr/local/lib/python3.13/site-packages/airtouch4pyapi/airtouch.py", line 65, in UpdateInfo
    await self.SendMessageToAirtouch(message)
  File "/usr/local/lib/python3.13/site-packages/airtouch4pyapi/airtouch.py", line 251, in SendMessageToAirtouch
    return self.TranslatePacketToMessage(dataResult)
                                         ^^^^^^^^^^
UnboundLocalError: cannot access local variable 'dataResult' where it is not associated with a value
2025-01-04 20:08:07.156 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [140334064600256] Entity fan.family does not support action fan.turn_on

**Comment by nathanvdh** [comment]
This is something I fixed for the main climate entity but I forgot to do the same for the fan entitys. I don't have an environment I can test properly in atm but I've made the change that should fix this and created a 0.2.9 update - give it a go.

**Comment by rgogada** [comment]
> This is something I fixed for the main climate entity but I forgot to do the same for the fan entitys. I don't have an environment I can test properly in atm but I've made the change that should fix this and created a 0.2.9 update - give it a go.

Just re-downloaded the add on which downloaded the 0.2.9 and everything seems to work again. Thanks a lot for taking time. Really appreciate it. Cheers.

**Comment by Seellr07** [comment]
Thanks mate, appreciate your time!

**Comment by TotallyNotACyborg** [comment]
After having come across this issue, I too appreciate your time!
